<a href="https://colab.research.google.com/github/pperorin/CE/blob/main/3D/Sem2/Intro%20Data%20Ana/Quiz6/Quiz6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQcU3V0vzjMAgq6kkB_GKjaxlIcLmdiLOT_ZmHUOB6Q4GnJI4K24Ypyocz4-TpePK9XEONRFQ14FS07/pub?gid=0&single=true&output=csv")
df

User   M1   M2   M3   M4   M5   M6  Average
0   Alice  NaN  2.0  3.0  NaN  1.0  5.0     2.75
1     Bob  5.0  NaN  3.0  1.0  NaN  2.0     2.75
2   Cindy  1.0  3.0  NaN  2.0  1.0  4.0     2.20
3     Dan  2.0  NaN  3.0  NaN  3.0  5.0     3.25
4     Eve  NaN  3.0  5.0  2.0  NaN  2.0     3.00
5    Fern  4.0  1.0  NaN  2.0  5.0  NaN     3.00
6  George  NaN  3.0  4.0  2.0  NaN  5.0     3.50

In [ ]:
alice = df.loc[[0],["M3","M6"]]
bob = df.loc[[1],["M3","M6"]]
corr = np.corrcoef(alice, bob)
corr

array([[ 1., -1.],
       [-1.,  1.]])

In [ ]:
alice = df.loc[[0],["M2","M5","M6"]]
cindy = df.loc[[2],["M2","M5","M6"]]
corr = np.corrcoef(alice, cindy)
corr

array([[1.        , 0.89104211],
       [0.89104211, 1.        ]])

In [ ]:
alice = df.loc[[0],["M3","M5","M6"]]
dan = df.loc[[3],["M3","M5","M6"]]
corr = np.corrcoef(alice, dan)
corr

array([[1.       , 0.8660254],
       [0.8660254, 1.       ]])

In [ ]:
alice = df.loc[[0],["M2","M3","M6"]]
eve = df.loc[[4],["M2","M3","M6"]]
corr = np.corrcoef(alice, eve)
corr

array([[ 1. , -0.5],
       [-0.5,  1. ]])

In [ ]:
alice = df.loc[[0],["M2","M5"]]
fern = df.loc[[5],["M2","M5"]]
corr = np.corrcoef(alice, fern)
corr

array([[ 1., -1.],
       [-1.,  1.]])

In [ ]:
alice = df.loc[[0],["M2","M3","M6"]]
george = df.loc[[6],["M2","M3","M6"]]
corr = np.corrcoef(alice, george)
corr

array([[1.        , 0.98198051],
       [0.98198051, 1.        ]])